{% set version = "0.3.0dev" %}
{% set name = "fpylll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fpylll/releases/download/{{ version }}/fpylll-{{ version }}.tar.gz
  sha256: 75303197286c0a5f5b123dcf01304585902c4e7031b30a5c70edbfc28327278b

build:
  number: 2
  skip: true  # [win]
  script:
    # https://github.com/conda-forge/toolchain-feedstock/pull/11
    - export CPPFLAGS="-I${PREFIX}/include ${CPPFLAGS}"
    - python setup.py install

requirements:
  build:
    - toolchain
    - cython
    - pkg-config
    - gmp >=5.0.1,<7.0
    - mpfr 4.*
    - qd 2.3.*
    - fplll 5.2.*
    - cysignals
    - numpy 1.11.*
    - python
  run:
    - gmp >=5.0.1,<7.0
    - mpfr 4.*
    - qd 2.3.*
    - fplll 5.2.*
    - cysignals
    - numpy >=1.11
    - python

test:
  requires:
    - pytest
  commands:
    - py.test
  imports:
    - fpylll
  source_files:
    - tests/*

about:
  home: https://github.com/fplll/fpylll
  license: GPLv2+
  license_file: LICENSE
  summary: A Python (2 and 3) wrapper for fplll.
  dev_url: https://github.com/fplll/fpylll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
