{% set version = "0.4.1dev" %}
{% set name = "fpylll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fpylll/releases/download/{{ version }}/fpylll-{{ version }}.tar.gz
  sha256: b2024cb3b03ebd2ca64f4ccea1a38110dc51d38ff62ad720de598ef23946a7eb

build:
  number: 1000
  skip: true  # [win]
  script:
    - python setup.py install

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - cython
    - gmp
    - mpfr
    - qd
    - fplll
    - cysignals
    - numpy
    - python
  run:
    - gmp
    - mpfr
    - qd
    - fplll
    - cysignals
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pytest
  commands:
    - py.test --disable-pytest-warnings
  imports:
    - fpylll
  source_files:
    - tests/*

about:
  home: https://github.com/fplll/fpylll
  license: GPLv2+
  license_file: LICENSE
  summary: A Python (2 and 3) wrapper for fplll.
  dev_url: https://github.com/fplll/fpylll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
